---
- hosts: windows
  vars:
    myAnalogSitePath: "E:\\inetpub\\My"
    staging_path: "E:\\download"    
    env: "DEV"
    ReleaseVersion: "{{ deployversion }}"
    envFolder: "env-specific"
    bkpPath: "E:\\Backup"
  tasks:
  - name: Downloading latest release to staging folder
    win_get_url:
      url: http://nwd2jenkinspoc1:9095/MyAnalog/{{ ReleaseVersion }}.zip
      dest: E:\Download\
      force_basic_auth: yes
      url_username: svc_easdevops_deploy
      url_password: Pass@word!
  - name: Unzip latest release file in staging folder
    win_unzip:
      src: "{{ staging_path }}\\{{ ReleaseVersion }}.zip"
      dest: "{{ staging_path }}\\{{ ReleaseVersion }}"      
    tags: unzip
  - name: Take Backup of website folder
    win_copy:
      src: "{{ myAnalogSitePath }}\\"
      dest: "{{ bkpPath }}\\"
      remote_src: yes
  - name: Copying Environment Specific files to website folder
    win_copy:
      src: "{{ staging_path }}\\{{ ReleaseVersion }}\\{{envFolder}}\\{{env}}"
      dest: "{{ myAnalogSitePath }}\\"
      remote_src: yes
  - name: Clean up Environment Specific
    win_file:
      path: "{{ staging_path }}\\{{ ReleaseVersion }}\\{{envFolder}}"
      state: absent
  - name: Copying Deployment files to website folder
    win_copy:
      src: "{{ staging_path }}\\{{ ReleaseVersion }}\\"
      dest: "{{ myAnalogSitePath }}\\"
      remote_src: yes
